backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    fields:
      - { label: "Order", name: "order", widget: "number"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Responsibilities", name: "responsibilities", widget: "string" }
      - { label: "Git", name: "git", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - label: "Tech"
        name: "tech"
        widget: "list"
        fields:
          - {label: "Technology", name: "technology", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image" }
  - name: "ancillary"
    label: "ancillary"
    folder: "src/pages/ancillary"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        default: "ancillary"
      - label: "Skills"
        name: "skills"
        widget: "list"
        fields:
          - {label: "Skill", name: "skill", widget: "string" }
      - { label: "Picture", name: "picture", widget: "image" }
      - { label: "Github", name: "github", widget: "string" }
      - { label: "Linkedin", name: "linkedin", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "About", name: "about", widget: "string" }