backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "description", widget: "string"}